/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#b6c4ff",
        "on-primary": "#ffffff",
        "on-primary-container": "#90a8ff",
        secondary: "#505f76",
        surface: "#f7f9fb",
        "tertiary-fixed": "#acedff",
        "on-tertiary-container": "#1dbcda",
        "outline-variant": "#c5c5d3",
        "surface-container-low": "#f2f4f6",
        "primary-fixed": "#dce1ff",
        "on-primary-fixed": "#00164e",
        outline: "#757682",
        error: "#ba1a1a",
        "on-tertiary": "#ffffff",
        "on-surface": "#191c1e",
        "on-secondary-container": "#54647a",
        "on-surface-variant": "#444651",
        tertiary: "#002f38",
        "inverse-surface": "#2d3133",
        "surface-container-highest": "#e0e3e5",
        "surface-variant": "#e0e3e5",
        "tertiary-container": "#004754",
        "on-tertiary-fixed": "#001f26",
        "primary-container": "#1e3a8a",
        "surface-dim": "#d8dadc",
        "surface-container-lowest": "#ffffff",
        "on-background": "#191c1e",
        "secondary-container": "#d0e1fb",
        "on-primary-fixed-variant": "#264191",
        "on-secondary-fixed": "#0b1c30",
        "tertiary-fixed-dim": "#4cd7f6",
        "surface-tint": "#4059aa",
        "on-secondary-fixed-variant": "#38485d",
        "surface-bright": "#f7f9fb",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed-variant": "#004e5c",
        "error-container": "#ffdad6",
        primary: "#00236f",
        "on-error": "#ffffff",
        "inverse-on-surface": "#eff1f3",
        "on-error-container": "#93000a",
        "inverse-primary": "#b6c4ff",
        "surface-container-high": "#e6e8ea",
        background: "#f7f9fb",
        "surface-container": "#eceef0",
        "secondary-fixed": "#d3e4fe",
        "secondary-fixed-dim": "#b7c8e1",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        sm: "10px",
        gutter: "20px",
        md: "20px",
        xl: "48px",
        "container-max": "1280px",
        xs: "4px",
        lg: "28px",
        base: "8px",
      },
      fontFamily: {
        "headline-lg": ["ui-sans-serif", "system-ui", "sans-serif"],
        "body-lg": ["ui-sans-serif", "system-ui", "sans-serif"],
        "headline-lg-mobile": ["ui-sans-serif", "system-ui", "sans-serif"],
        "body-md": ["ui-sans-serif", "system-ui", "sans-serif"],
        "label-md": ["ui-sans-serif", "system-ui", "sans-serif"],
        "display-lg-mobile": ["ui-sans-serif", "system-ui", "sans-serif"],
        "display-lg": ["ui-sans-serif", "system-ui", "sans-serif"],
        "headline-md": ["ui-sans-serif", "system-ui", "sans-serif"],
      },
      fontSize: {
        "headline-lg": ["22px", { lineHeight: "1.22", fontWeight: "600" }],
        "body-lg": ["14px", { lineHeight: "1.55", fontWeight: "400" }],
        "headline-lg-mobile": ["24px", { lineHeight: "1.2", fontWeight: "600" }],
        "body-md": ["13.5px", { lineHeight: "1.55", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "1.35", letterSpacing: "0.035em", fontWeight: "500" }],
        "display-lg-mobile": ["28px", { lineHeight: "1.15", letterSpacing: "-0.01em", fontWeight: "700" }],
        "display-lg": ["32px", { lineHeight: "1.12", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-md": ["16px", { lineHeight: "1.28", fontWeight: "600" }],
      },
    },
  },
  plugins: [require("@tailwindcss/forms"), require("@tailwindcss/container-queries")],
};
